// ============================================================================
// games/aces/server/src/room.ts — S_ROOM: the ACES room lifecycle integrator.
//
// Owns: the phase machine (lobby -> live -> end -> auto-restart live, same
// seed), seat/bot-fill bookkeeping, the TICK_RATE interval, input intake
// (latest-wins, stale-seq dropped HERE — the World trusts us, see world.ts
// header note), the respawn queue, tickets/scoring, debug verbs, and snapshot
// + event broadcast. The World (S_SIM) knows nothing about phases, tickets,
// sockets or time — every cross-boundary fact flows through the narrow seam
// documented at each call site.
//
// Tick order (FIXED):
//   roomTick -> [lobby: countdown | live: simTick | end: restart dwell]
//            -> pending-score flush -> snapshot cadence (every other tick)
//   simTick  -> match clock -> World.step(dt) -> event flush (+kill
//            bookkeeping / tickets / win) -> respawn queue
//
// Clocks: everything gameplay-coupled counts WORLD/ROOM TICKS, never wall
// time — the debug `tick` verb fast-forwards the sim without moving the wall
// clock, so a mixed clock would desync the respawn queue and match timer
// under e2e fast-forward. Date.now() appears only where wall time IS the
// point: input staleness (STALE_SECONDS) and the 1/s scoreboard rate limit
// (RULES 3 sanctions Date.now for clocks).
//
// Deviation note (reported): CONTRACT §4 S_ROOM says "the room never mints"
// ids/codes, but the FROZEN GameRoomHandle requires `readonly id` populated
// by the room and platform/server/src/lobby.ts keys rooms by room.id and its
// private-create path documents "code generated by the room" — no injection
// path exists. House precedent (outpost/rift) mints both locally; we do the
// same using the RULES 3 identity exception: crypto.randomUUID() only, never
// Math.random.
// ============================================================================
import {
  BOT_CLASS_WEIGHTS,
  BOT_DIFFICULTY,
  BOT_NAMES,
  CLASSES,
  END_SECONDS,
  GAME_ID,
  GAME_NAME,
  LOBBY_COUNTDOWN_S,
  MAP_SEED,
  MATCH_SECONDS,
  MAX_PLAYERS,
  PLANE_CLASSES,
  RESPAWN_SECONDS,
  SNAP_RATE,
  STALE_SECONDS,
  TICKETS_TO_WIN,
  TICK_RATE,
} from '@aces/shared/config';
import type { PlaneClassId, RoomSettings, TeamId } from '@aces/shared/config';
import { buildMap, mulberry32 } from '@aces/shared/maps';
import type { AcesMap } from '@aces/shared/maps';
import { parseC2S, validateSettings } from '@aces/shared/protocol';
import type {
  C2S,
  EventMsg,
  PhaseMsg,
  S2C,
  SnapPlane,
  SnapshotMsg,
  WelcomeMsg,
} from '@aces/shared/protocol';
import type { GameEvent, InputFrame, KillEvent, MatchPhase, PlaneState, ScoreRow } from '@aces/shared/types';
import type { GameRoomHandle, PlayerId, RoomId, RoomInfo, RoomIO, Visibility } from '@platform/shared';
import { World } from './world.js';
import { computeIntent, type BotMem } from './bots.js';

// ---- derived clocks (single derivation point; seconds -> ticks) ------------
const TICK_DT_S = 1 / TICK_RATE;
/** SNAP_RATE divides TICK_RATE evenly (30/15) — snapshot every other tick. */
const SNAP_EVERY_TICKS = Math.max(1, Math.round(TICK_RATE / SNAP_RATE));
const RESPAWN_TICKS = Math.ceil(RESPAWN_SECONDS * TICK_RATE); // 105 ticks = 3.5 s
const MATCH_TICKS = MATCH_SECONDS * TICK_RATE;
const END_TICKS = END_SECONDS * TICK_RATE;
const LOBBY_TICKS = LOBBY_COUNTDOWN_S * TICK_RATE;
/** Debug `tick` verb ceiling (CONTRACT §4: N ≤ 600). */
const DEBUG_TICK_MAX = 600;
const SCORE_LIMIT_MS = 1000;

/**
 * FNV-1a over the bot's roster name. The contract specifies per-bot seeds as
 * hashStr(botName)+roundSeed, but @platform/shared exports no hashStr and the
 * Import Law forbids reaching into the client's visual.ts for one — so this
 * is the server-local definition (same shape as rift's hashSeed, which made
 * the identical call). Only determinism is required, not cross-compatibility.
 */
function hashStr(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** Weighted BOT_CLASS_WEIGHTS roll on the caller's stream. Walks classes in
 *  declared order (scout .30 → fighter .50 → gunship .20, sums to 1) and
 *  falls through to fighter only if floats conspire against the sum. */
function pickBotClass(next: () => number): PlaneClassId {
  const roll = next();
  let acc = 0;
  for (const cls of PLANE_CLASSES) {
    acc += BOT_CLASS_WEIGHTS[cls];
    if (roll < acc) return cls;
  }
  return 'fighter';
}

/**
 * One seat — a chair in the room, human or bot. The World's PlaneState is the
 * PHYSICS truth; this is the MEMBERSHIP truth (bot flag, input echo seq,
 * respawn queue, personal kill tallies). Linked 1:1 by id: every seat has
 * exactly one plane (via World.addPlayer) and no plane exists without a
 * seat. Map insertion order is join order, keeping roster/snapshot row order
 * stable across ticks.
 */
interface Seat {
  id: PlayerId;
  name: string;
  bot: boolean;
  team: TeamId;
  /** Personal tallies off KillEvents — World.stats carries only shots/hits. */
  kills: number;
  deaths: number;
  /** Last APPLIED input seq — echoed back on the owner's snapshot rows. */
  lastSeq: number;
  /** Wall-clock ms of last applied input — drives stalePlayers() ONLY. */
  lastInputAtMs: number;
  /** Dead and inside the respawn flow (picker wait / bot re-pick). */
  awaitingRespawn: boolean;
  /** World tick at which RESPAWN_SECONDS has elapsed for this death. */
  respawnReadyTick: number;
  /** Human's early class pick (sent before the respawn timer cleared). */
  pendingCls: PlaneClassId | null;
  /** Bot-only deterministic stream (class rolls); null for humans. */
  botRng: (() => number) | null;
}

export class AcesRoom implements GameRoomHandle {
  readonly id: RoomId;
  readonly code: string | null;
  readonly visibility: Visibility;

  private readonly io: RoomIO;
  private readonly settings: Required<RoomSettings>;
  /** Built once from the frozen MAP_SEED — terrain never varies across rounds. */
  private readonly map: AcesMap;
  /**
   * Round seed for the World's combat stream. Auto-restart law: "fresh live
   * with tickets reset (same room, same seed)" — MAP_SEED forever, so every
   * round is byte-reproducible given the same input sequence.
   */
  private readonly roundSeed = MAP_SEED;
  /** INTEG wiring: persistent pilot memory per bot id (S_BOTS contract). */
  private readonly botMems = new Map<PlayerId, BotMem>();

  private readonly seats = new Map<PlayerId, Seat>();
  private botSeq = 0;

  private phase: MatchPhase = 'lobby';
  private winner: TeamId | null = null;
  /** Lobby countdown armed? (Only the first human arrival arms it.) */
  private lobbyArmed = false;
  private lobbyRemainTick = 0;
  private matchRemainTick = MATCH_TICKS;
  private endRemainTick = 0;
  /** Sudden death: clock expired on a tie — phase stays live, next kill wins. */
  private suddenDeath = false;

  private world: World;
  private tickets: { royal: number; iron: number } = { royal: 0, iron: 0 };

  private timer: ReturnType<typeof setInterval> | null = null;
  private roomTickCount = 0;
  private pendingScore = false;
  private lastScoreMs = 0;

  /** Pooled SnapPlane rows keyed by plane id — mutated in place per snapshot. */
  private readonly rowPool = new Map<string, SnapPlane>();
  /** Preallocated per-human snapshot shells (house pattern: mutate in place,
   *  send; io.send JSON-encodes synchronously so reuse-after-send is safe). */
  private readonly snapShells = new Map<PlayerId, SnapshotMsg>();

  constructor(visibility: Visibility, io: RoomIO, settings?: Record<string, unknown>) {
    this.visibility = visibility;
    this.io = io;
    // Single settings gate (frozen shared validator): coerces/defaults rather
    // than throws, so every room always has a fully-typed settings record.
    this.settings = validateSettings(settings);

    // Identity only (RULES 3 exception): randomUUID, never Math.random.
    this.id = crypto.randomUUID();
    this.code =
      visibility === 'private' ? crypto.randomUUID().replace(/-/g, '').slice(0, 5).toUpperCase() : null;

    this.map = buildMap(MAP_SEED);
    this.world = new World(this.map, this.settings, this.roundSeed);

    // Bots seat BEFORE any human arrives so the very first roster view shows
    // a full squadron (CONTRACT §4: "bots already seated and visible").
    if (this.settings.botFill) this.fillBots();
  }

  // -------------------------------------------------------------------------
  // GameRoomHandle — every member guarded: one bad message/tick must never
  // throw across the socket boundary or kill the interval.
  // -------------------------------------------------------------------------

  info(): RoomInfo {
    return {
      id: this.id,
      code: this.code,
      game: GAME_ID,
      label: GAME_NAME,
      // Connected HUMANS only — a bot-filled room must not browse as "full";
      // humans displace bots, so bots must never count toward fullness.
      players: this.humanCount(),
      maxPlayers: MAX_PLAYERS,
      phase: this.phase,
      visibility: this.visibility,
    };
  }

  playerCount(): number {
    return this.humanCount();
  }

  /** Humans with no APPLIED input for > STALE_SECONDS (the platform closes
   *  their sockets). Bots excluded: they have no socket to close, and their
   *  future inputs come from bot brains (S_BOTS), not liveness signals. */
  stalePlayers(): PlayerId[] {
    const now = Date.now();
    const out: PlayerId[] = [];
    for (const s of this.seats.values()) {
      if (s.bot) continue;
      if (now - s.lastInputAtMs > STALE_SECONDS * 1000) out.push(s.id);
    }
    return out;
  }

  addPlayer(id: PlayerId, name: string, _resume?: PlayerId, _sig?: string): void {
    try {
      const existing = this.seats.get(id);
      if (existing !== undefined) {
        // Duplicate join of a held seat: refresh name, resend welcome.
        // resume/sig REBIND is OUT OF SCOPE v1 (CONTRACT §5 C_NET): a dropped
        // socket mints a fresh seat — a bot has usually taken the old one.
        existing.name = name;
        existing.lastInputAtMs = Date.now();
        this.sendWelcome(id);
        return;
      }

      // Humans take a bot's slot (CONTRACT §4). Target the team the newcomer
      // would balance onto, so displacement can never skew team sizes.
      let team = this.smallerTeam();
      if (this.settings.botFill) {
        const victim = this.pickDisplaceableBot(team);
        if (victim !== undefined) {
          this.destroySeat(victim);
          team = this.smallerTeam(); // recount after freeing the slot
        }
      }
      // Genuinely full (botFill off, or zero bots left to displace). The ACES
      // S2C union defines no error message → rejection stays silent, the same
      // law as parseC2S garbage.
      if (this.seats.size >= this.capacity()) return;

      this.createSeat(id, name, team, false, null);
      this.world.addPlayer(id, name, team, false);

      // Spawn law: lobby join = seat + countdown only; mid-live join =
      // auto-spawn FIGHTER instantly; end-phase join = seat only (the
      // imminent restart — ≤ END_SECONDS away — spawns them via the normal
      // live transition, keeping ONE transition code path). Welcome goes out
      // LAST so the joiner's very first snapshot of truth already carries the
      // armed countdown / live clock rather than a pre-arm zero.
      if (this.phase === 'live') {
        this.world.spawn(id, 'fighter');
      } else if (this.phase === 'lobby' && !this.lobbyArmed) {
        // First human arms the LOBBY_COUNTDOWN_S (MIN_PLAYERS is 1).
        this.lobbyArmed = true;
        this.lobbyRemainTick = LOBBY_TICKS;
        this.broadcastPhase();
      }
      this.sendWelcome(id);
      this.sendScore(true);
    } catch (err) {
      console.error('[aces] addPlayer failed', err);
    }
  }

  /**
   * v1 has no rejoin (CONTRACT §5), so permanent=true and socket-drop
   * removals are identical: the seat dies and — botFill on — a bot inherits
   * the slot immediately ("humans leaving hand the plane back to a bot").
   * The refilled bot spawns instantly mid-live, mirroring the mid-live human
   * spawn rule, so team strength never dips while the scoreboard runs.
   */
  removePlayer(id: PlayerId, _permanent?: boolean): void {
    try {
      const seat = this.seats.get(id);
      if (seat === undefined) return;
      const wasBot = seat.bot;
      this.destroySeat(seat);
      if (!wasBot) {
        if (this.settings.botFill && this.seats.size < this.capacity()) {
          this.addBot(this.smallerTeam());
        }
        // A countdown with nobody left to play dies quietly; PhaseMsg is the
        // ONLY phase channel, so cancellation announces there too (endsAtS 0).
        if (this.phase === 'lobby' && this.lobbyArmed && this.humanCount() === 0) {
          this.lobbyArmed = false;
          this.lobbyRemainTick = 0;
          this.broadcastPhase();
        }
        this.sendScore(true);
      }
    } catch (err) {
      console.error('[aces] removePlayer failed', err);
    }
  }

  handleMessage(id: PlayerId, msg: unknown): void {
    try {
      // Single validation gate. Debug verbs open ONLY for debug rooms
      // (settings.debug === true) — parseC2S enforces that, so the switch
      // below can trust that any DebugMsg here arrived legally.
      const parsed = parseC2S(msg, this.settings.debug === true);
      if (parsed === null) return; // malformed/garbage: ignore in silence
      switch (parsed.t) {
        case 'input':
          this.handleInput(id, parsed);
          return;
        case 'spawn':
          this.handleSpawnPick(id, parsed.cls);
          return;
        case 'ping':
          this.io.send(id, { t: 'pong', ts: parsed.ts }); // pure passthrough
          return;
        case 'debug':
          this.handleDebug(id, parsed.cmd, parsed.x, parsed.y);
          return;
        default:
          return;
      }
    } catch (err) {
      console.error('[aces] handleMessage failed', err);
    }
  }

  start(): void {
    if (this.timer !== null) return; // idempotent
    this.timer = setInterval(() => this.tickGuarded(), 1000 / TICK_RATE);
  }

  stop(): void {
    if (this.timer !== null) {
      clearInterval(this.timer);
      this.timer = null;
    }
  }

  // -------------------------------------------------------------------------
  // Tick driver
  // -------------------------------------------------------------------------

  private tickGuarded(): void {
    try {
      this.roomTick();
    } catch (err) {
      console.error('[aces] tick failed', err); // one bad tick never kills the interval
    }
  }

  private roomTick(): void {
    this.roomTickCount++;
    if (this.phase === 'lobby') {
      if (this.lobbyArmed && --this.lobbyRemainTick <= 0) this.goLive();
    } else if (this.phase === 'live') {
      this.simTick();
    } else {
      // end: scoreboard dwell, then auto-restart into fresh live (same seed).
      if (--this.endRemainTick <= 0) this.goLive();
    }
    // Rate-limited scoreboard flush (streak churn can kill faster than 1/s).
    if (this.pendingScore && Date.now() - this.lastScoreMs >= SCORE_LIMIT_MS) this.sendScore();
    // Snapshot cadence runs in EVERY phase: clients anchor clocks, rosters
    // and tickets off snapshots, and lobby/end have no other periodic channel.
    if (this.roomTickCount % SNAP_EVERY_TICKS === 0) this.sendSnapshots();
  }

  /**
   * Exactly one World tick plus everything hanging off it. Also the body of
   * the debug `tick` fast-forward verb, so CI advances the sim through the
   * SAME path the interval uses — there is no second code path to diverge.
   */
  /**
   * INTEG plug point (S_ROOM × S_BOTS seam): one computeIntent call per living
   * bot per tick, feeding world.setInput. Memory persists across deaths within
   * a round; a fresh round wipes it with everything else.
   */
  private driveBots(): void {
    if (!this.settings.botFill || this.seats.size === 0) return;
    const diff = BOT_DIFFICULTY[this.settings.difficulty];
    const planes = this.world.planes;
    const bullets = this.world.bullets;
    for (const seat of this.seats.values()) {
      if (!seat.bot || seat.botRng === null) continue;
      const p = this.world.planes.find((q) => q.id === seat.id);
      if (p === undefined || p.dead) continue;
      let mem = this.botMems.get(seat.id);
      if (mem === undefined) {
        mem = { targetId: null, reactT: 0, weavePhase: (hashStr(seat.name) % 997) / 997 };
        this.botMems.set(seat.id, mem);
      }
      const frame = computeIntent(
        { self: p, others: planes, bullets, map: this.map },
        diff,
        seat.botRng,
        mem,
        TICK_DT_S,
      );
      this.world.setInput(p.id, frame);
    }
  }

  private simTick(): void {
    this.matchRemainTick--;
    if (this.matchRemainTick <= 0 && !this.suddenDeath) {
      // Time-expiry win check: higher tickets wins; a tie flips sudden death
      // (phase stays LIVE, clock reads 0, next credited kill ends the match).
      const winner: TeamId | null =
        this.tickets.royal > this.tickets.iron
          ? 'royal'
          : this.tickets.iron > this.tickets.royal
            ? 'iron'
            : null;
      if (winner === null) {
        this.suddenDeath = true;
      } else {
        this.endMatch(winner);
        return;
      }
    }

    this.driveBots(); // INTEG: bot intents land BEFORE the step that consumes them
    const events = this.world.step(TICK_DT_S); // World returns its reused buffer — consume now
    this.processEvents(events);
    if (this.phase !== 'live') return; // that step's kill just ended the match
    this.processRespawns();
  }

  // -------------------------------------------------------------------------
  // Events: flushed immediately as EventMsg; kills additionally drive room
  // bookkeeping (tallies, respawn queue, tickets, win/sudden-death checks).
  // -------------------------------------------------------------------------

  private processEvents(events: readonly GameEvent[]): void {
    for (const ev of events) {
      if (ev.kind === 'kill') this.applyKill(ev);
      this.broadcastEvent(ev);
    }
  }

  private applyKill(ev: KillEvent): void {
    // Victim: deaths always count (crashes too); enter the respawn queue.
    const victim = this.seats.get(ev.victim);
    if (victim !== undefined) {
      victim.deaths++;
      victim.awaitingRespawn = true;
      victim.respawnReadyTick = this.world.tick + RESPAWN_TICKS;
      victim.pendingCls = null; // picker re-opens fresh after every death
    }
    // CONTRACT scoring law: crash (burn) credits NO killer and moves NO
    // ticket — tickets move only on credited kills.
    if (!ev.crash) {
      const killer = this.seats.get(ev.killer);
      if (killer !== undefined) killer.kills++;
      this.tickets[ev.killerTeam]++;
      // Sudden death: teams were tied at expiry, so ANY credited kill is
      // decisive by construction. Otherwise the standard TICKETS_TO_WIN gate.
      if (this.suddenDeath || this.tickets[ev.killerTeam] >= TICKETS_TO_WIN) {
        this.endMatch(ev.killerTeam);
      }
    }
    this.queueScore(); // board changed (kills/deaths at minimum)
  }

  // -------------------------------------------------------------------------
  // Respawn queue. Humans: RESPAWN_SECONDS then wait INDEFINITELY for the
  // class picker ("your last class pre-selected" is the client's display
  // concern — the server spawns only on an explicit {t:'spawn'}). Bots pick
  // by BOT_CLASS_WEIGHTS on their own seeded stream the moment the timer
  // clears. Tick-based (not wall-based) so debug fast-forward stays coherent.
  // -------------------------------------------------------------------------

  private processRespawns(): void {
    for (const seat of this.seats.values()) {
      if (!seat.awaitingRespawn) continue;
      if (this.world.tick < seat.respawnReadyTick) continue;
      if (seat.bot && seat.botRng !== null) {
        this.world.spawn(seat.id, pickBotClass(seat.botRng));
        seat.awaitingRespawn = false;
      } else if (!seat.bot && seat.pendingCls !== null) {
        this.world.spawn(seat.id, seat.pendingCls);
        seat.awaitingRespawn = false;
        seat.pendingCls = null;
      }
    }
  }

  private handleSpawnPick(id: PlayerId, cls: PlaneClassId): void {
    const seat = this.seats.get(id);
    if (seat === undefined || seat.bot) return;
    const plane = this.world.planes.find((p) => p.id === id);
    if (plane === undefined || !plane.dead) return; // alive: re-picks happen per spawn only
    if (!seat.awaitingRespawn) return; // lobby/end seating: spawn LAW owns first spawns
    if (this.world.tick >= seat.respawnReadyTick) {
      this.world.spawn(id, cls);
      seat.awaitingRespawn = false;
      seat.pendingCls = null;
    } else {
      seat.pendingCls = cls; // early pick, honored by processRespawns at readiness
    }
  }

  // -------------------------------------------------------------------------
  // Input intake: latest-wins per player; stale/duplicate seq dropped HERE
  // (World.setInput stores whatever it is handed — world.ts header note).
  // Forwarding straight into World.setInput is equivalent to "feed intents at
  // TICK_RATE": step() reads each plane's frame once per tick, so only the
  // latest frame ever integrates.
  // -------------------------------------------------------------------------

  private handleInput(id: PlayerId, msg: Extract<C2S, { t: 'input' }>): void {
    const seat = this.seats.get(id);
    if (seat === undefined || seat.bot) return;
    if (msg.seq <= seat.lastSeq) return; // stale/duplicate
    seat.lastSeq = msg.seq;
    seat.lastInputAtMs = Date.now();
    this.world.setInput(id, msg); // InputMsg is structurally an InputFrame (+ `t`)
  }

  // -------------------------------------------------------------------------
  // Debug verbs — reachable ONLY when parseC2S allowed them, i.e. the room
  // was created with settings.debug === true. All server-authoritative.
  // -------------------------------------------------------------------------

  private handleDebug(id: PlayerId, cmd: string, x: number | undefined, y: number | undefined): void {
    switch (cmd) {
      case 'god':
        this.world.applyGod(id); // toggle that player's no-damage flag
        return;
      case 'warp':
        // A teleport needs both coordinates; half-specified warps are garbage.
        if (x !== undefined && y !== undefined) this.world.applyWarp(id, x, y);
        return;
      case 'crate':
        // Coordinates optional — the World rejection-samples open water itself.
        this.world.forceCrate(x, y);
        return;
      case 'tick': {
        // Fast-forward N sim ticks (CI/e2e). Live-only: stepping the World in
        // lobby/end would run the crate spawner outside a match and fight the
        // phase machine. The loop re-checks phase every iteration so a burst
        // stops the moment it fast-forwards PAST the winning ticket.
        if (this.phase !== 'live') return;
        const n = Math.min(DEBUG_TICK_MAX, Math.max(0, Math.floor(x ?? 1)));
        for (let i = 0; i < n && this.phase === 'live'; i++) this.simTick();
        return;
      }
    }
  }

  // -------------------------------------------------------------------------
  // Phase machine
  // -------------------------------------------------------------------------

  /**
   * Fresh live round: rebuild the World (SAME seed — auto-restart law), re-
   * seat everyone, reset tickets/tallies, auto-spawn every seated pilot —
   * humans as FIGHTER (picker available from then on), bots by weighted roll
   * on their private streams. Phase changes ride ONLY PhaseMsg.
   */
  private goLive(): void {
    this.world = new World(this.map, this.settings, this.roundSeed);
    this.botMems.clear();
    for (const s of this.seats.values()) {
      if (s.bot && s.botRng !== null) s.botRng = mulberry32((hashStr(s.name) + this.roundSeed) >>> 0);
    }
    for (const s of this.seats.values()) {
      this.world.addPlayer(s.id, s.name, s.team, s.bot);
      s.kills = 0;
      s.deaths = 0;
      s.awaitingRespawn = false;
      s.pendingCls = null;
    }
    this.tickets = { royal: 0, iron: 0 };
    this.suddenDeath = false;
    this.matchRemainTick = MATCH_TICKS;
    this.phase = 'live';
    this.winner = null;
    for (const s of this.seats.values()) {
      this.world.spawn(s.id, s.bot && s.botRng !== null ? pickBotClass(s.botRng) : 'fighter');
    }
    this.lobbyArmed = false;
    this.broadcastPhase();
    this.sendScore(true);
  }

  private endMatch(winner: TeamId): void {
    this.phase = 'end';
    this.winner = winner;
    this.endRemainTick = END_TICKS;
    this.broadcastPhase();
  }

  /** Match-relative seconds remaining in the CURRENT phase — the ONE source
   *  for both PhaseMsg.endsAtS and snapshot timeLeftS (two derivations are
   *  how clocks drift apart). Sudden death reports 0 by design: the HUD
   *  stamps SUDDEN DEATH off timeLeftS===0 while phase stays live. */
  private phaseSeconds(): number {
    if (this.phase === 'lobby') return this.lobbyArmed ? this.lobbyRemainTick / TICK_RATE : 0;
    if (this.phase === 'live') return Math.max(0, this.matchRemainTick / TICK_RATE);
    return Math.max(0, this.endRemainTick / TICK_RATE);
  }

  private broadcastPhase(): void {
    const msg: PhaseMsg = { t: 'phase', phase: this.phase, endsAtS: this.phaseSeconds() };
    if (this.phase === 'end' && this.winner !== null) msg.winner = this.winner;
    this.broadcast(msg);
  }

  // -------------------------------------------------------------------------
  // Seats & bots
  // -------------------------------------------------------------------------

  private capacity(): number {
    return this.settings.teamSize * 2;
  }

  private humanCount(): number {
    let n = 0;
    for (const s of this.seats.values()) if (!s.bot) n++;
    return n;
  }

  /** Smaller team by SEAT count (bots included — balance is about squadrons,
   *  not sockets). Ties go royal, matching rift's tie-break convention. */
  private smallerTeam(): TeamId {
    let royal = 0;
    let iron = 0;
    for (const s of this.seats.values()) {
      if (s.team === 'royal') royal++;
      else iron++;
    }
    return royal <= iron ? 'royal' : 'iron';
  }

  private createSeat(
    id: PlayerId,
    name: string,
    team: TeamId,
    bot: boolean,
    botRng: (() => number) | null,
  ): Seat {
    const seat: Seat = {
      id,
      name,
      bot,
      team,
      kills: 0,
      deaths: 0,
      lastSeq: 0,
      lastInputAtMs: Date.now(), // fresh joins are not instantly stale
      awaitingRespawn: false,
      respawnReadyTick: 0,
      pendingCls: null,
      botRng,
    };
    this.seats.set(id, seat);
    if (!bot) {
      // Humans get a preallocated snapshot shell (mutated in place forever).
      this.snapShells.set(id, {
        t: 'snapshot',
        tick: 0,
        phase: 'lobby',
        timeLeftS: 0,
        tickets: { royal: 0, iron: 0 },
        planes: [],
        bullets: [],
        crates: [],
      });
    }
    return seat;
  }

  private destroySeat(seat: Seat): void {
    this.seats.delete(seat.id);
    this.snapShells.delete(seat.id);
    this.rowPool.delete(seat.id);
    // Stats survive inside World on purpose (scoreboard may outlive a socket)
    // but the PLANE must go with the seat or snapshots would list ghosts.
    this.world.removePlayer(seat.id);
  }

  /** Bot seat a joining human may displace: prefer one on the joiner's target
   *  team (keeps balance), fall back to any bot (all-human one-side edge). */
  private pickDisplaceableBot(team: TeamId): Seat | undefined {
    const bots = [...this.seats.values()].filter((s) => s.bot);
    return bots.find((s) => s.team === team) ?? bots[0];
  }

  /** Fill every empty seat to teamSize*2 with named bots, balanced across
   *  teams (CONTRACT §4). BOT_NAMES has 12 entries vs ≤8 seats, so the
   *  fallback below is defensive only. */
  private fillBots(): void {
    while (this.seats.size < this.capacity()) this.addBot(this.smallerTeam());
  }

  private addBot(team: TeamId): void {
    const name = this.nextBotName();
    const id = `bot-${this.botSeq++}`;
    // Per-bot stream: hashStr(botName)+roundSeed per CONTRACT §4 S_ROOM.
    const rng = mulberry32((hashStr(name) + this.roundSeed) >>> 0);
    this.createSeat(id, name, team, true, rng);
    this.world.addPlayer(id, name, team, true);
    // Mirror the mid-live human rule: a refilled bot takes off immediately.
    if (this.phase === 'live') this.world.spawn(id, pickBotClass(rng));
  }

  private nextBotName(): string {
    const used = new Set<string>();
    for (const s of this.seats.values()) if (s.bot) used.add(s.name);
    for (const name of BOT_NAMES) if (!used.has(name)) return name;
    return `Bot ${this.botSeq}`; // unreachable at ≤8 seats vs 12 names
  }

  // -------------------------------------------------------------------------
  // Wire: broadcast helpers, welcome, score, snapshots
  // -------------------------------------------------------------------------

  /** One shared message object per event: io.send JSON-encodes synchronously,
   *  so every recipient can safely share the same reference. */
  private broadcastEvent(ev: GameEvent): void {
    const msg: EventMsg = { t: 'event', e: ev };
    this.broadcast(msg);
  }

  private broadcast(msg: S2C): void {
    for (const s of this.seats.values()) {
      if (!s.bot) this.io.send(s.id, msg); // bots have no session behind them
    }
  }

  private sendWelcome(id: PlayerId): void {
    const msg: WelcomeMsg = {
      t: 'welcome',
      id,
      seed: this.map.seed, // client rebuilds identical terrain from this
      tickRate: TICK_RATE,
      snapRate: SNAP_RATE,
      phase: this.phase,
      timeLeftS: this.phaseSeconds(),
      tickets: { royal: this.tickets.royal, iron: this.tickets.iron },
      settings: this.settings,
      roster: this.scoreRows(),
    };
    this.io.send(id, msg);
  }

  private queueScore(): void {
    this.pendingScore = true;
    this.sendScore(); // attempt immediate send; rate limit decides
  }

  /** Scoreboard broadcast. force=true bypasses the 1/s limiter (membership
   *  changes and round starts are rare and authoritative); otherwise sends
   *  only when pending AND ≥1s since the last — streak churn coalesces. */
  private sendScore(force = false): void {
    if (!force) {
      if (!this.pendingScore) return;
      if (Date.now() - this.lastScoreMs < SCORE_LIMIT_MS) return;
    }
    this.pendingScore = false;
    this.lastScoreMs = Date.now();
    this.broadcast({ t: 'score', board: this.scoreRows() });
  }

  /** One row per seat: personal kills/deaths (room tracking off KillEvents)
   *  merged with shots/hits (World.stats), scored as kills*100 + hits*2. */
  private scoreRows(): ScoreRow[] {
    const rows: ScoreRow[] = [];
    for (const seat of this.seats.values()) {
      const plane = this.world.planes.find((p) => p.id === seat.id);
      const st = this.world.stats.get(seat.id);
      const hits = st?.hits ?? 0;
      rows.push({
        id: seat.id,
        name: seat.name,
        team: seat.team,
        cls: plane?.cls ?? 'fighter',
        bot: seat.bot,
        kills: seat.kills,
        deaths: seat.deaths,
        shots: st?.shots ?? 0,
        hits,
        score: seat.kills * 100 + hits * 2,
      });
    }
    return rows;
  }

  // -------------------------------------------------------------------------
  // Snapshots: every other room tick (= SNAP_RATE at TICK_RATE), in ALL
  // phases. Plane rows are POOL objects mutated in place and SHARED across
  // recipients — except the seq echo, which is per-recipient: set own row →
  // send (sync JSON encode) → reset. Snapshot/event literals crossing the
  // wire are allocation-exempt (RULES 4), bullets/crates are copied per beat.
  // -------------------------------------------------------------------------

  private sendSnapshots(): void {
    const w = this.world;
    const rows: SnapPlane[] = [];
    for (const seat of this.seats.values()) {
      const plane = w.planes.find((p) => p.id === seat.id);
      if (plane === undefined) continue; // cannot happen while seats/planes are 1:1
      const row = this.rowFor(plane);
      row.seq = 0; // shared default; echoed per-recipient below
      rows.push(row);
    }
    const bulletRows = w.bullets.map((b) => ({ id: b.id, team: b.team, x: b.x, y: b.y, vx: b.vx, vy: b.vy }));
    const crateRows = w.crates.map((c) => ({ ...c }));
    const tick = w.tick;
    const phase = this.phase;
    const timeLeftS = this.phaseSeconds();
    const tickets = { royal: this.tickets.royal, iron: this.tickets.iron };

    for (const seat of this.seats.values()) {
      if (seat.bot) continue;
      const msg = this.snapShells.get(seat.id);
      if (msg === undefined) continue;

      const plane = w.planes.find((p) => p.id === seat.id);
      if (plane !== undefined && !plane.dead) {
        let you = msg.you;
        if (you === undefined) {
          you = { ...this.rowFor(plane) }; // private copy — carries its own seq echo
          msg.you = you;
        } else {
          fillRow(you, plane);
        }
        you.seq = seat.lastSeq; // "last input seq the server had applied"
      } else {
        delete msg.you; // dead/spectating: omitted per SnapshotMsg contract
      }

      msg.tick = tick;
      msg.phase = phase;
      msg.timeLeftS = timeLeftS;
      msg.tickets = tickets;
      msg.planes = rows;
      msg.bullets = bulletRows;
      msg.crates = crateRows;

      const own = rows.find((r) => r.id === seat.id);
      if (own !== undefined) own.seq = seat.lastSeq;
      this.io.send(seat.id, msg);
      if (own !== undefined) own.seq = 0; // restore shared state post-encode
    }
  }

  private rowFor(p: PlaneState): SnapPlane {
    let row = this.rowPool.get(p.id);
    if (row === undefined) {
      row = {
        id: p.id, name: '', team: p.team, cls: p.cls, bot: p.bot,
        x: 0, y: 0, h: 0, sp: 0, vx: 0, vy: 0, hp: 0, maxHp: 0, heat: 0,
        jammed: false, boost: 0, boosting: false, throttle: 0, invulnT: 0,
        dead: true, streak: 0, seq: 0,
      };
      this.rowPool.set(p.id, row);
    }
    fillRow(row, p);
    return row;
  }
}

/** Mutate a pooled row in place from live plane state. maxHp is derived from
 *  the class table (PlaneState carries no maxHp — CLASSES.hp IS the max). */
function fillRow(r: SnapPlane, p: PlaneState): void {
  r.id = p.id;
  r.name = p.name;
  r.team = p.team;
  r.cls = p.cls;
  r.bot = p.bot;
  r.x = p.x;
  r.y = p.y;
  r.h = p.h;
  r.sp = Math.hypot(p.vx, p.vy);
  r.vx = p.vx;
  r.vy = p.vy;
  r.hp = p.hp;
  r.maxHp = CLASSES[p.cls].hp;
  r.heat = p.heat;
  r.jammed = p.jammed;
  r.boost = p.boost;
  r.boosting = p.boosting;
  r.throttle = p.throttle;
  r.invulnT = p.invulnT;
  r.dead = p.dead;
  r.streak = p.streak;
}
